version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: mi_nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/index.html:/usr/share/nginx/html/index.html
    networks:
      - mi_red

  mysql:
    image: mysql:latest
    container_name: mi_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mi_base_de_datos
      MYSQL_USER: user  # No usar root aquí
      MYSQL_PASSWORD: root
    ports:
      - "3307:3306"
    networks:
      - mi_red

  app:
    build: ./app
    container_name: mi_app
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: mi_base_de_datos
    depends_on:
      - mysql
    ports:
      - "3000:3000"
    networks:
      - mi_red
    volumes:
      - ./nginx/index.html:/usr/src/app/index.html  # Se monta en la app también

networks:
  mi_red:
    driver: bridge
